/// Flutter icons VoiceIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VoiceIcons
///      fonts:
///       - asset: fonts/VoiceIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VoiceIcons {
  VoiceIcons._();

  static const _kFontFam = 'VoiceIcons';
  static const String? _kFontPkg = null;

  static const IconData group_1171275562 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconLine = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconPremium = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btnBack = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btnClose = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
